import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className="bg-background">
        <Toaster
          position="top-center"
          duration={10000}
          expand
          theme="light"
          closeButton
          richColors
        />
        <main>{children}</main>
      </body>
    </html>
  );
}
